[build]
  publish = "."
  command = "pip install -r requirements.txt && streamlit run app.py"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
